
services:
  recipes:
    build: ../svc-recipes
    env_file:
      - ../svc-recipes/.test.env
    ports:
      - 8008:8008
    depends_on:
      - db
 
  ingredients:
    build: ../svc-ingredients
    env_file:
      - ../svc-ingredients/.test.env
    ports:
      - 8009:8008
    depends_on:
      - db
 
  db:
    image: postgres:15-bookworm
    volumes:
      - colunch_data:/var/lib/postgresql/data/
    env_file:
      - .test.env
    ports:
      - 5432:5432
 
volumes:
    colunch_data:
