alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
ingress:
  rules:
    - component:
        name: recipes-org-svc-recipes
      match:
        path:
          prefix: /
name: colunch-dev
region: lon
services:
  - envs:
      - key: RECIPES_HOST
        scope: RUN_AND_BUILD_TIME
        value: 0.0.0.0
      - key: RECIPES_PORT
        scope: RUN_AND_BUILD_TIME
        value: "8080"
    http_port: 8080
    image:
      deploy_on_push: {}
      registry_type: DOCR
      repository: recipes-org/svc-recipes
      tag: 0.1.0
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /docs
      success_threshold: 3
      period_seconds: 5
    name: recipes-org-svc-recipes
