alerts:
- rule: DEPLOYMENT_FAILED
- rule: DEPLOYMENT_LIVE
- rule: DOMAIN_FAILED
- rule: DOMAIN_LIVE
databases:
- cluster_name: colunch-dev
  db_name: defaultdb
  db_user: doadmin
  engine: PG
  name: colunch-dev
  production: true
  version: "15"
domains:
- domain: dev.colunch.app
  type: PRIMARY
  zone: colunch.app
ingress:
  rules:
  - component:
      name: recipes-org-svc-recipes
    match:
      path:
        prefix: /
name: colunch-dev
region: lon
services:
- envs:
  - key: RECIPES_HOST
    scope: RUN_AND_BUILD_TIME
    value: 0.0.0.0
  - key: RECIPES_PORT
    scope: RUN_AND_BUILD_TIME
    value: "8080"
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${colunch-dev.DATABASE_URL}
  health_check:
    http_path: /docs
    period_seconds: 5
    success_threshold: 3
  http_port: 8080
  image:
    deploy_on_push: {}
    registry_type: DOCR
    repository: recipes-org/svc-recipes
    tag: 0.1.0
  instance_count: 1
  instance_size_slug: basic-xxs
  name: recipes-org-svc-recipes
