---
name: Dev DB Migrations Apply

on:
  push:
    branches: [ "main" ]
    paths:
      - dev/do/migrations/*
  workflow_dispatch:

env:
  FORCE_COLOR: ${{ vars.FORCE_COLOR }}

jobs:
  deploy:
    name: Dev DB Migrations Apply
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -sSf https://atlasgo.sh | sh
      - run: |
          atlas migrate apply \
            --dir "file://dev/do/migrations/" \
            --url "${{ secrets.DEV_DB_URL }}" \
            --revisions-schema public
      - run: |
          cp dev/do/db.hcl live/do/db.hcl
          cp dev/do/migrations/* live/do/migrations/
      - run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
      - uses: peter-evans/create-pull-request@v5
        with:
          title: Deploy DB LIVE ${{ env.SHA_SHORT }}
          add-paths: live/do/*
          token: ${{ secrets.COLUNCH_INFRA_DB_DEV_GHA }}
          branch: db-live/${{ env.SHA_SHORT }}
          base: ${{ github.head_ref }}
